#Configuration#
#Reasons not to add special equipmemt#
#If true reason to disables usage#
Reason:
  Spawner: true
  Egg: true
#Mobs drop the all the equipment they're wearing#
#If false will on drop only special items#
DropFix:
  Equipment: false  
Precentages:
  ChancePerSpawn: 3
Tier:
  Legendary:
    Color: gold
    Chance: 3
    Enchaments:
      Amt: 7
      Levels: 10
  Lore:
    Color: grey
    Chance: 3
    Enchaments:
      Amt: 7
      Levels: 9
  Magical:
    Color: blue
    Chance: 3
    Enchaments:
      Amt: 3
      Levels: 4
  Rare:
    Color: red
    Chance: 3
    Enchaments:
      Amt: 5
      Levels: 5
  Set:
    Color: green
    Chance: 3
    Enchaments:
      Amt: 7
      Levels: 6
  ##Custom:
    ##Color:
    ##Chance:
    ##Enchaments:
      ##Amt: 7
      ##Levels: 6
#If enabled only worlds listed will be affected#
Worlds:
  Enabled: false
  Allowed:
  - 'world'
  - 'world_nether'
  - 'world_the_end'