#Configuration#
#Reasons not to add special equipmemt#
#If true reason to disables usage#
Reason:
  Spawner: true
  Egg: true
#Mobs drop the all the equipment they're wearing#
#If false will on drop only special items#
DropFix:
  Equipment: false  
Precentages:
  ChancePerSpawn: 3
Legendary:
  Enchaments:
    Amt: 7
    Levels: 10
Lore:
  Enchaments:
    Amt: 7
    Levels: 9
Magical:
  Enchaments:
    Amt: 3
    Levels: 4
Rare:
  Enchaments:
    Amt: 5
    Levels: 5
Set:
  Enchaments:
    Amt: 7
    Levels: 6