name: DiabloDrops
main: com.modcrafting.diablodrops.DiabloDrops
version: 0.6
website: http://modcrafting.com
authors: [Deathmarine,Nunnery]
description: >
             Plugin for Bukkit.
commands:
    diablodrops:
        description: Allows user to spawn a type of item.
        aliases: [dd, ddrops, diablod]
        usage: /<command> [type]
        permission: diablodrops.dd
permissions:
    diablodrops.dd:
        description: Allows user to spawn a type of item.
        default: op
